services:
  - type: web
    name: ai-health-translator-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
